Update polymer-tinymce.html so it works with gulp
Fixed so it can be used in gulp scripts avoiding the following error whene executin gulp (uglify-js module) 
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token punc «(», expected punc «:» (line: 82, col: 13, pos: 2042)
Unglify needs ES5 code, ES6 syntax will make it fail.